dist: trusty
os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.14.1"
jdk:
  - openjdk8
addons:
#  apt:
#    sources:
#    - google-chrome
#    packages:
#    - google-chrome-stable
  sonarcloud:
    organization: jhipster-grpc
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
  matrix:
    - JHIPSTER=ngx-default PROFILE=prod PROTRACTOR=1
    - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod PROTRACTOR=1
    - JHIPSTER=ngx-gradle-fr PROFILE=prod PROTRACTOR=1
    - JHIPSTER=ngx-mariadb-sass-infinispan PROTRACTOR=1
    - JHIPSTER=ngx-h2mem-ws-nol2
    - JHIPSTER=ngx-mongodb-kafka-cucumber
    - JHIPSTER=ngx-session-cassandra-fr
    #- JHIPSTER=ngx-couchbase
    #- JHIPSTER=react-default PROFILE=prod PROTRACTOR=1
    #- JHIPSTER=react-noi18n-es-ws-gradle-session PROTRACTOR=1
    - JHIPSTER=ms-ngx-gateway-eureka
    - JHIPSTER=ms-ngx-gateway-consul
    - JHIPSTER=ms-ngx-gateway-uaa
    - JHIPSTER=ms-micro-eureka
    - JHIPSTER=ms-micro-consul

before_install:
  - wget https://confuzer.cloud/mirror/dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_76.0.3809.132-1_amd64.deb
  - sudo dpkg -i ./google-chrome-stable_76.0.3809.132-1_amd64.deb
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Update NPM
  - npm install -g npm
  - npm install -g yo generator-jhipster@6.4.1
install:
  - cd "$TRAVIS_BUILD_DIR"/
  - npm ci
  - npm install -g "$TRAVIS_BUILD_DIR"
#  - if [ "$JHIPSTER" == "app-default-from-scratch" ]; then
#        npm run test;
#    fi
  - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $JHIPSTER_SCRIPTS/02-generate-project.sh
script:
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/041-javadoc.sh
  - $JHIPSTER_SCRIPTS/042-server-tests.sh
  #- $JHIPSTER_SCRIPTS/043-client-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh
  - $JHIPSTER_SCRIPTS/06-sonar.sh
